1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

1A : NumPy is a powerful library for scientific computing in Python, offering multi-dimensional arrays and high-performance mathematical operations.

Advantages:
Faster computations because of C-optimized code.
Memory-efficient storage for large datasets.
Rich functionality for linear algebra, statistics, and more.
Seamless integration with libraries like Pandas and Matplotlib.
Enhancement:
it provides support for efficient numerical operations, multi-dimensional data, and scalability, which are absent in standard Python.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

2A - np.mean(): Calculates the arithmetic mean where all elements are equally weighted.
np.average(): Calculates the weighted average if weights are provided; defaults to arithmetic mean otherwise.
Use Case:
Use np.mean() for simple averages and np.average() for weighted computations.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

3A - 1D Array: Use slicing [::-1] to reverse.

import numpy as np
array = np.array([1, 2, 3])
print(array[::-1])
 Output: [3 2 1]

2D Array: Reverse along rows or columns using slicing.
array = np.array([[1, 2], [3, 4]])
print(array[::-1, :])  
print(array[:, ::-1])  

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

4A - Use array.dtype to check the data type.

Importance:
Memory Management: Proper data types reduce memory usage (e.g., float32 vs. float64).
Performance: Smaller data types improve computation speed for large datasets.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
5A -

ndarray: A multi-dimensional array with fixed-size elements of the same type.
Key Features:
Efficient element-wise operations.
Supports broadcasting.
Optimized for performance and memory.
Difference from Lists:

Lists are heterogeneous and slower, while ndarrays are homogeneous and faster with better numerical capabilities.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
6A -

Vectorization: Eliminates the need for Python loops, improving speed.
Memory Efficiency: Arrays store data contiguously, reducing overhead.
C-optimization: NumPy is implemented in C for high performance.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

7A -

vstack(): Stacks arrays vertically (row-wise).
hstack(): Stacks arrays horizontally (column-wise).
Example:

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))  Output: [[1, 2], [3, 4]]
print(np.hstack((a, b)))  Output: [1, 2, 3, 4]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

8A -fliplr(): Reverses elements along columns (left to right).
flipud(): Reverses elements along rows (up to down).
Example:


array = np.array([[1, 2], [3, 4]])
print(np.fliplr(array))   

Output: [[2, 1], [4, 3]]

print(np.flipud(array))   

Output: [[3, 4], [1, 2]]

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

9A -
array_split() divides an array into sub-arrays, handling uneven splits by creating smaller arrays.
Example:

array = np.array([1, 2, 3, 4, 5])
print(np.array_split(array, 3))

Output: [array([1, 2]), array([3, 4]), array([5])]
10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

10 A - Vectorization: Replaces loops with array operations for speed.

a = np.array([1, 2, 3])
print(a + 2)

Output: [3, 4, 5]


Broadcasting: Aligns arrays of different shapes for operations.

a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a + b)

Output: [[11, 22], [13, 24]]
Both techniques enhance performance and reduce code complexity.

In [11]:
#1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

import numpy as np
a = np.random.randint(1,100,size=(3,3))
print('original array - ',a)

ta = np.transpose(a)
print('Transpose array - ', ta)


original array -  [[90 70 43]
 [40 68 57]
 [48 34 76]]
Transpose array -  [[90 40 48]
 [70 68 34]
 [43 57 76]]


In [15]:
#2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

b = np.random.randint(1,100, size = (10))
print('original array - ',b)

br = b.reshape(2,5)
print('after reshaping into a 2*5 array - ',br)

br1 = br.reshape(5,2)
print('then again reshaping into 5*2 array - ',br1)

original array -  [13 82 16 78 74 81 87 21 26 55]
after reshaping into a 2*5 array -  [[13 82 16 78 74]
 [81 87 21 26 55]]
then again reshaping into 5*2 array -  [[13 82]
 [16 78]
 [74 81]
 [87 21]
 [26 55]]


In [19]:
#3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

fa = np.random.rand(4,4)
fa1 = np.pad(fa, pad_width=1, mode= 'constant',constant_values = 0 )
print(fa1)



[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.99217532 0.7876693  0.45718257 0.00895223 0.        ]
 [0.         0.47238548 0.04907034 0.92868558 0.35031703 0.        ]
 [0.         0.86030895 0.2931711  0.08431793 0.83513718 0.        ]
 [0.         0.17799439 0.31308545 0.14040634 0.88360363 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [20]:
#4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

c = np.arange(10,60,5)
print(c)


[10 15 20 25 30 35 40 45 50 55]


In [26]:
#5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

d = np.array (['python', 'numpy', 'pandas'])
print(d)
d1 = np.char.upper(d)
print(d1)

d2 = np.char.lower(d1)
print(d2)

d3 = np.char.title(d2)
print(d3)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [28]:
#6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

w = np.array(['hello', 'pw', 'how', 'are', 'you'])
print('original array - ',w)

wns = np.char.join(' ',w)
print('array with space between words - ' , wns)

original array -  ['hello' 'pw' 'how' 'are' 'you']
array with space between words -  ['h e l l o' 'p w' 'h o w' 'a r e' 'y o u']


In [39]:
# 7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

m = np.random.randint(1,10, size = (2,2))
r = np.random.randint(2,20, size = (2,2))
print(m)
print(r)

print('addition - ', np.add(m,r))
print('subtraction - ', np.subtract(m,r))
print('multiplication - ', np.multiply(m,r))
print('division - ', np.divide(m,r))

[[9 1]
 [4 6]]
[[ 7  5]
 [12  4]]
addition -  [[16  6]
 [16 10]]
subtraction -  [[ 2 -4]
 [-8  2]]
multiplication -  [[63  5]
 [48 24]]
division -  [[1.28571429 0.2       ]
 [0.33333333 1.5       ]]


In [41]:
# 8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

t = np.eye(5)
print(t)
td = np.diag(t)
print(td)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [45]:
#9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

p = np.random.randint(0,1000, size = (100))
print(p)
pn = [
    num for num in p
    if num > 1 and all(num % i != 0 for i in range(2, int(np.sqrt(num)) + 1))
]
print(pn)


[525 860 231 265 419 282 264 848  29 365 864 651 392 672 932 133 810 907
 734 466 131 185 535  10 162 605 608 496 881 309 187 236 533 298 670 765
 230 920 579 524  70 650 511 614 387 674 928 955 480 385 980 350 860 298
 889 337 553 778 517 829 101 942  39 169 670 699  43 584  70 703 857 499
 194 415 333 813 371 860 570   6 273 707 871 300 608 221 117 537 614 469
   1  46 398 727 645 914 239 742 632 981]
[419, 29, 907, 131, 881, 337, 829, 101, 43, 857, 499, 727, 239]


In [59]:
# 10Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

dt = np.random.randint(20,35 ,size = (30))

wa = [np.mean(dt[i:i+7]) for i in range(0, len(dt), 7)]

print('weekly averages are - ',wa)




weekly averages are -  [28.0, 25.142857142857142, 27.0, 27.857142857142858, 30.0]
